{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authplane.secretsName" . }}
  labels:
    {{- include "authplane.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ (.Values.secrets.sessionSecret | default (randAlphaNum 64)) | b64enc | quote }}
  admin-api-key: {{ (.Values.secrets.adminApiKey | default (randAlphaNum 64)) | b64enc | quote }}
  {{- if .Values.secrets.connectStateSecret }}
  connect-state-secret: {{ .Values.secrets.connectStateSecret | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and (eq (toString .Values.config.storage.driver) "postgres") (not .Values.postgresql.enabled) .Values.externalDatabase.host (not .Values.externalDatabase.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-extdb" (include "authplane.fullname" .) }}
  labels:
    {{- include "authplane.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}

{{- if and (eq (toString .Values.config.data_encryption.driver) "aes_master") (not .Values.secrets.dataEncryption.existingSecret) .Values.secrets.dataEncryption.aesMasterKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authplane.aesMasterSecretName" . }}
  labels:
    {{- include "authplane.labels" . | nindent 4 }}
type: Opaque
data:
  aes-master-key: {{ .Values.secrets.dataEncryption.aesMasterKey | b64enc | quote }}
  {{- if .Values.secrets.dataEncryption.aesMasterOldKey }}
  aes-master-old-key: {{ .Values.secrets.dataEncryption.aesMasterOldKey | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.vault.signing.enabled (not .Values.vault.signing.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authplane.vaultSigningSecretName" . }}
  labels:
    {{- include "authplane.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.vault.signing.auth.method "token" }}
  vault-token: {{ .Values.vault.signing.auth.token | b64enc | quote }}
  {{- else if eq .Values.vault.signing.auth.method "approle" }}
  vault-approle-role-id: {{ .Values.vault.signing.auth.approle.roleId | b64enc | quote }}
  vault-approle-secret-id: {{ .Values.vault.signing.auth.approle.secretId | b64enc | quote }}
  {{- end }}
{{- end }}
