{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authplane.configSecretName" . }}
  labels:
    {{- include "authplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
{{- end }}
