// Package cmd wires up the cobra command tree for docsgen.
//
// The root command exposes a shared --out flag that holds the output
// directory for generated reference docs. Subcommands inherit this flag
// and resolve their own target file underneath it.
package cmd

import (
	"github.com/spf13/cobra"
)

// DefaultOutDir is the default directory where generated reference docs
// land. Callers may override with --out.
const DefaultOutDir = "docs/reference"

// GeneratedByHeader is the canonical first line that every generated file
// must start with. The docs-check tooling greps for this marker to
// distinguish hand-written from machine-written reference pages.
const GeneratedByHeader = "<!-- generated by tools/docsgen; do not edit. Re-run: make docs-gen -->"

// NewRoot returns the root cobra command with all subcommands attached.
// It is exported so main and tests can construct a fresh command tree.
func NewRoot() *cobra.Command {
	root := &cobra.Command{
		Use:   "docsgen",
		Short: "Generate reference documentation for the Authplane authserver",
		Long: `docsgen inspects the authserver source tree and produces reference
documentation (CLI flags, HTTP API, environment variables, configuration).

Each subcommand emits a single Markdown file under --out. The 'all'
subcommand runs every generator in sequence.`,
		SilenceUsage: true,
	}

	root.PersistentFlags().String("out", DefaultOutDir, "output directory for generated reference docs")

	root.AddCommand(newCLICmd())
	root.AddCommand(newHTTPCmd())
	root.AddCommand(newEnvCmd())
	root.AddCommand(newConfigCmd())
	root.AddCommand(newOpenAPICmd())
	root.AddCommand(newAllCmd())

	return root
}
